# Generated by Django 4.2.4 on 2023-11-03 23:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
