# Generated by Django 4.2.4 on 2023-10-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('Member', 'Участник'), ('Admin', 'Администратор'), ('Moderator', 'Модератор')], default='Member', max_length=9),
        ),
    ]
