# Generated by Django 4.2.4 on 2023-11-04 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_is_active_remove_user_roles_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Token',
        ),
    ]
