# Generated by Django 4.2.4 on 2023-10-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='порядковый номер модуля')),
                ('title', models.CharField(max_length=150, verbose_name='название модуля')),
                ('description', models.TextField(verbose_name='описание модуля')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['id'],
            },
        ),
    ]
