# Generated by Django 4.2.4 on 2023-10-27 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='порядковый'
                                                            'номер модуля')),
                ('title', models.CharField(max_length=150,
                                           verbose_name='название модуля')),
                ('description', models.TextField(verbose_name='описание модуля')),
                ('is_paid', models.BooleanField(default=False,
                                                verbose_name='Модуль оплачен')),
            ],
            options={
                'verbose_name': 'Модуль',
                'verbose_name_plural': 'Модули',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='порядковый номер раздела')),
                ('title', models.CharField(max_length=150,
                                           verbose_name='название раздела')),
                ('description', models.TextField(verbose_name='описание раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='порядковый номер темы')),
                ('title', models.CharField(max_length=150, verbose_name='название темы')),
                ('description', models.TextField(verbose_name='описание темы')),
                ('section',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics',
                                   to='main.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
                'ordering': ['id'],
            },
        ),
    ]
