# Generated by Django 4.2.4 on 2023-11-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_module_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
