# Generated by Django 4.2.4 on 2023-10-25 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_section_module_is_paid_topic_section_module_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id'], 'verbose_name': 'Тема', 'verbose_name_plural': 'Темы'},
        ),
    ]
